//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kwld.FluxorAnalyser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kwld.FluxorAnalyser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor component should inherit Fluxor component base.
        /// </summary>
        internal static string FLX001_Description {
            get {
                return ResourceManager.GetString("FLX001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component {0} should inherit {1}.
        /// </summary>
        internal static string FLX001_Message {
            get {
                return ResourceManager.GetString("FLX001_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluxor component inheritance.
        /// </summary>
        internal static string FLX001_Title {
            get {
                return ResourceManager.GetString("FLX001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluxor feature state should have FeatureStateAttribute.
        /// </summary>
        internal static string FLX002_Description {
            get {
                return ResourceManager.GetString("FLX002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is used as feature state, should be decorated with {1}.
        /// </summary>
        internal static string FLX002_Message {
            get {
                return ResourceManager.GetString("FLX002_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature State should be decorated.
        /// </summary>
        internal static string FLX002_Title {
            get {
                return ResourceManager.GetString("FLX002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature state object should have a default constructor (need not be public)..
        /// </summary>
        internal static string FLX003_Description {
            get {
                return ResourceManager.GetString("FLX003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature State &apos;{0}&apos; missing default constructor.
        /// </summary>
        internal static string FLX003_Message {
            get {
                return ResourceManager.GetString("FLX003_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature state default constructor.
        /// </summary>
        internal static string FLX003_Title {
            get {
                return ResourceManager.GetString("FLX003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect methods should return Task.
        /// </summary>
        internal static string FLX004_Description {
            get {
                return ResourceManager.GetString("FLX004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect method {0} should return Task.
        /// </summary>
        internal static string FLX004_Message {
            get {
                return ResourceManager.GetString("FLX004_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect method return type.
        /// </summary>
        internal static string FLX004_Title {
            get {
                return ResourceManager.GetString("FLX004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect method must either take action as argument, or declare action in the EffectsAttribute constructor..
        /// </summary>
        internal static string FLX005_Description {
            get {
                return ResourceManager.GetString("FLX005_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect method {0} has not defined its action..
        /// </summary>
        internal static string FLX005_Message {
            get {
                return ResourceManager.GetString("FLX005_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect method missing action.
        /// </summary>
        internal static string FLX005_Title {
            get {
                return ResourceManager.GetString("FLX005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect methods should include a IDispatcher argument..
        /// </summary>
        internal static string FLX006_Description {
            get {
                return ResourceManager.GetString("FLX006_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect method {0} missing IDispatcher argument..
        /// </summary>
        internal static string FLX006_Message {
            get {
                return ResourceManager.GetString("FLX006_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect method should use IDispatcher.
        /// </summary>
        internal static string FLX006_Title {
            get {
                return ResourceManager.GetString("FLX006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect methods should consume action as first parameter.
        /// </summary>
        internal static string FLX007_Description {
            get {
                return ResourceManager.GetString("FLX007_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect method {0} should consume action as first parameter, or declare action in EffectAttribute constructor.
        /// </summary>
        internal static string FLX007_Message {
            get {
                return ResourceManager.GetString("FLX007_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect method argument order.
        /// </summary>
        internal static string FLX007_Title {
            get {
                return ResourceManager.GetString("FLX007_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer methods must either take a action as a argument, or .
        /// </summary>
        internal static string FLX008_Description {
            get {
                return ResourceManager.GetString("FLX008_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer method {0} should consume a action as first argument; or declare the  action type in ReducerMethodAttribute constructor.
        /// </summary>
        internal static string FLX008_Message {
            get {
                return ResourceManager.GetString("FLX008_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer method missing action.
        /// </summary>
        internal static string FLX008_Title {
            get {
                return ResourceManager.GetString("FLX008_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer methods must take a feature state argument..
        /// </summary>
        internal static string FLX009_Description {
            get {
                return ResourceManager.GetString("FLX009_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer method {0} is missing a feature state parameter..
        /// </summary>
        internal static string FLX009_Message {
            get {
                return ResourceManager.GetString("FLX009_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer method missing feature state.
        /// </summary>
        internal static string FLX009_Title {
            get {
                return ResourceManager.GetString("FLX009_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer methods must take a feature state argument..
        /// </summary>
        internal static string FLX010_Description {
            get {
                return ResourceManager.GetString("FLX010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer method {0} is missing a feature state parameter..
        /// </summary>
        internal static string FLX010_Message {
            get {
                return ResourceManager.GetString("FLX010_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer method missing feature state.
        /// </summary>
        internal static string FLX010_Title {
            get {
                return ResourceManager.GetString("FLX010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer methods should be pure functions, best implemented as a static method..
        /// </summary>
        internal static string FLX011_Description {
            get {
                return ResourceManager.GetString("FLX011_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer method {0} should be a static pure function..
        /// </summary>
        internal static string FLX011_Message {
            get {
                return ResourceManager.GetString("FLX011_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducer method should be static.
        /// </summary>
        internal static string FLX011_Title {
            get {
                return ResourceManager.GetString("FLX011_Title", resourceCulture);
            }
        }
    }
}
